=== clemi2408/tsdb_beta/schema/src/main/resources/api/model/worker/workerConfiguration.json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "type" : "object",
  "properties" : {
    "workerName" : {
      "type" : "string",
      "nullable" : false
    },
    "workerUrl" : {
      "type" : "string",
      "nullable" : false,
      "format": "uri",
      "pattern": "^https?://"
    },
    "workerThreads" : {
      "type" : "integer",
      "nullable" : false
    },
    "workerPercentage" : {
      "type" : "integer",
      "nullable" : false
    },
    "tsdbEndpoints" : {
      "type" : "array",
      "nullable" : false,
      "items" : {
        "$ref": "workerTsdbEndpoint.json"
      },
      "minItems": 1
    }



  },
  "required": [ "workerName","workerUrl","workerThreads","workerPercentage","tsdbEndpoints" ]
}

=== clemi2408/tsdb_beta/schema/src/main/resources/api/model/examples/generated/WorkerConfiguration_2.json
{
  "workerName" : "influx-worker-1",
  "workerUrl" : "http://localhost:8082",
  "workerThreads" : 3,
  "workerPercentage" : 100,
  "tsdbEndpoints" : [ {
    "endpointName" : "influx-zoneA",
    "tsdbUrl" : "http://127.0.0.1:8086",
    "tsdbToken" : "YcqeMSEqzrvDsPevnsPA9fuES38RU-R9_y9UZ2gefEYaNJfVdUOVdj5NvrPpwNnmVuGoZSsqZ_jxnKx9dhdHYw==",
    "endpointPercentage" : 100
  } ]
}
