=== clemi2408/tsdb_beta/schema/src/main/resources/api/model/worker/workerConfig.json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "type" : "object",
  "properties" : {

    "workerUrl" : {
      "type" : "string",
      "nullable" : false
    },
    "workerThreads" : {
      "type" : "integer",
      "nullable" : false
    },
    "tsdbConnection": {
      "$ref": "workerTsdbConnection.json",
      "nullable" : false
    },
    "createStorage" : {
      "type" : "boolean",
      "nullable" : false
    },
    "cleanupStorage" : {
      "type" : "boolean",
      "nullable" : false
    }
  },
  "required": [ "workerUrl","workerThreads","cleanupStorage","createStorage","tsdbConnection" ]
}

=== clemi2408/tsdb_beta/schema/src/main/resources/api/model/examples/generated/WorkerConfig_1.json
{
  "workerUrl" : "http://localhost:8082",
  "workerThreads" : 3,
  "tsdbConnection" : {
    "tsdbType" : "INFLUX",
    "url" : "http://127.0.0.1:8086",
    "token" : "YcqeMSEqzrvDsPevnsPA9fuES38RU-R9_y9UZ2gefEYaNJfVdUOVdj5NvrPpwNnmVuGoZSsqZ_jxnKx9dhdHYw==",
    "connectionProperties" : {
      "bucketName" : "testbucket",
      "organisationName" : "testorg"
    }
  },
  "createStorage" : true,
  "cleanupStorage" : true
}
