=== clemi2408/tsdb_beta/schema/src/main/resources/api/model/orchestrator/orchestratorResultResponse.json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "type" : "object",
  "properties" : {
    "taskResults" : {
      "type" : "array",
      "nullable" : false,
      "items" : {
        "$ref": "../result/taskResult.json"
      },
      "minItems": 0
    },
    "status" : {
      "type" : "string",
      "enum" : [ "INCOMPLETE", "COMPLETE" ],
      "nullable" : false
    },
    "totalResultParts" : {
      "type" : "integer",
      "nullable" : false
    },
    "completedParts" : {
      "type" : "integer",
      "nullable" : false
    }
  },
  "required": [ "taskResults","status","totalResultParts","completedParts"]
}

=== clemi2408/tsdb_beta/schema/src/main/resources/api/model/examples/manual/orchestratorResultResponse_1.json
{
  "taskResults": [
    {
      "taskName": "Task: 1",
      "sourceInformation": {
        "url": "http://localhost:8082"
      },
      "threadName": "pool-1-thread-1",
      "record": {
        "kvPairs": [
          {
            "key": "l",
            "value": [
              "F"
            ]
          },
          {
            "key": "staticKeyDynStringValue",
            "value": [
              "EOImd"
            ]
          },
          {
            "key": "uqJ9Pe",
            "value": [
              "lr"
            ]
          },
          {
            "key": "staticKeyDynStringEnumDynValue",
            "value": [
              "n"
            ]
          },
          {
            "key": "X",
            "value": [
              "s-val2"
            ]
          },
          {
            "key": "staticKeyStaticStringEnumValues",
            "value": [
              "s-val2"
            ]
          },
          {
            "key": "8uRf",
            "value": [
              36
            ]
          },
          {
            "key": "staticKeyUniformIntegerValue",
            "value": [
              90
            ]
          },
          {
            "key": "staticKeyUniformDoubleValue",
            "value": [
              32.16767351970475
            ]
          },
          {
            "key": "J1",
            "value": [
              35
            ]
          },
          {
            "key": "staticKeyTriangleIntegerValue",
            "value": [
              41
            ]
          },
          {
            "key": "staticKeyTriangleDoubleValue",
            "value": [
              12.039425225300977
            ]
          },
          {
            "key": "4Pznx",
            "value": [
              10
            ]
          },
          {
            "key": "staticKeyGaussIntegerValue",
            "value": [
              10
            ]
          },
          {
            "key": "staticKeyGaussDoubleValue",
            "value": [
              8.809735006786822
            ]
          }
        ],
        "recordId": "d977cc9c-73e6-4cb3-9d50-c1e32a79aa41"
      },
      "durationInMs": 440,
      "timeFrame": {
        "startTimestamp": "2023-03-14T22:47:01.813617Z",
        "endTimestamp": "2023-03-14T22:47:02.254043Z"
      }
    },
    {
      "taskName": "Task: 2",
      "sourceInformation": {
        "url": "http://localhost:8082"
      },
      "threadName": "pool-1-thread-2",
      "record": {
        "kvPairs": [
          {
            "key": "s",
            "value": [
              "9"
            ]
          },
          {
            "key": "staticKeyDynStringValue",
            "value": [
              "SE12O"
            ]
          },
          {
            "key": "GGcmkyO",
            "value": [
              "2AN"
            ]
          },
          {
            "key": "staticKeyDynStringEnumDynValue",
            "value": [
              "TH"
            ]
          },
          {
            "key": "w",
            "value": [
              "s-val1"
            ]
          },
          {
            "key": "staticKeyStaticStringEnumValues",
            "value": [
              "s-val1"
            ]
          },
          {
            "key": "CMlX",
            "value": [
              25
            ]
          },
          {
            "key": "staticKeyUniformIntegerValue",
            "value": [
              88
            ]
          },
          {
            "key": "staticKeyUniformDoubleValue",
            "value": [
              26.898222895618584
            ]
          },
          {
            "key": "4b5gS",
            "value": [
              69
            ]
          },
          {
            "key": "staticKeyTriangleIntegerValue",
            "value": [
              47
            ]
          },
          {
            "key": "staticKeyTriangleDoubleValue",
            "value": [
              14.175441832314476
            ]
          },
          {
            "key": "KyFL",
            "value": [
              8
            ]
          },
          {
            "key": "staticKeyGaussIntegerValue",
            "value": [
              10
            ]
          },
          {
            "key": "staticKeyGaussDoubleValue",
            "value": [
              8.383300924998668
            ]
          }
        ],
        "recordId": "2ad15e57-ed73-4ebc-9fde-047fd87bf1a8"
      },
      "durationInMs": 440,
      "timeFrame": {
        "startTimestamp": "2023-03-14T22:47:01.813649Z",
        "endTimestamp": "2023-03-14T22:47:02.254043Z"
      }
    },
    {
      "taskName": "Task: 3",
      "sourceInformation": {
        "url": "http://localhost:8082"
      },
      "threadName": "pool-1-thread-3",
      "record": {
        "kvPairs": [
          {
            "key": "O",
            "value": [
              "dp"
            ]
          },
          {
            "key": "staticKeyDynStringValue",
            "value": [
              "txLYS"
            ]
          },
          {
            "key": "s2M2KbAA",
            "value": [
              "Y"
            ]
          },
          {
            "key": "staticKeyDynStringEnumDynValue",
            "value": [
              "SnL"
            ]
          },
          {
            "key": "s",
            "value": [
              "s-val1"
            ]
          },
          {
            "key": "staticKeyStaticStringEnumValues",
            "value": [
              "s-val1"
            ]
          },
          {
            "key": "ZUSK",
            "value": [
              64
            ]
          },
          {
            "key": "staticKeyUniformIntegerValue",
            "value": [
              34
            ]
          },
          {
            "key": "staticKeyUniformDoubleValue",
            "value": [
              19.126120120071484
            ]
          },
          {
            "key": "4bm",
            "value": [
              56
            ]
          },
          {
            "key": "staticKeyTriangleIntegerValue",
            "value": [
              58
            ]
          },
          {
            "key": "staticKeyTriangleDoubleValue",
            "value": [
              17.72636904950741
            ]
          },
          {
            "key": "vuY",
            "value": [
              10
            ]
          },
          {
            "key": "staticKeyGaussIntegerValue",
            "value": [
              8
            ]
          },
          {
            "key": "staticKeyGaussDoubleValue",
            "value": [
              4.9891541912536
            ]
          }
        ],
        "recordId": "b1bc4a21-4527-43b5-bc51-9e24eb9aef41"
      },
      "durationInMs": 440,
      "timeFrame": {
        "startTimestamp": "2023-03-14T22:47:01.813967Z",
        "endTimestamp": "2023-03-14T22:47:02.254046Z"
      }
    },
    {
      "taskName": "Task: 4",
      "sourceInformation": {
        "url": "http://localhost:8082"
      },
      "threadName": "pool-1-thread-3",
      "record": {
        "kvPairs": [
          {
            "key": "J",
            "value": [
              "Q"
            ]
          },
          {
            "key": "staticKeyDynStringValue",
            "value": [
              "1Gb6I"
            ]
          },
          {
            "key": "1ri0yBX",
            "value": [
              "l"
            ]
          },
          {
            "key": "staticKeyDynStringEnumDynValue",
            "value": [
              "gi"
            ]
          },
          {
            "key": "R",
            "value": [
              "s-val2"
            ]
          },
          {
            "key": "staticKeyStaticStringEnumValues",
            "value": [
              "s-val1"
            ]
          },
          {
            "key": "hB1",
            "value": [
              45
            ]
          },
          {
            "key": "staticKeyUniformIntegerValue",
            "value": [
              66
            ]
          },
          {
            "key": "staticKeyUniformDoubleValue",
            "value": [
              29.577374962965447
            ]
          },
          {
            "key": "DY",
            "value": [
              69
            ]
          },
          {
            "key": "staticKeyTriangleIntegerValue",
            "value": [
              70
            ]
          },
          {
            "key": "staticKeyTriangleDoubleValue",
            "value": [
              16.219275494242225
            ]
          },
          {
            "key": "cKd0",
            "value": [
              9
            ]
          },
          {
            "key": "staticKeyGaussIntegerValue",
            "value": [
              7
            ]
          },
          {
            "key": "staticKeyGaussDoubleValue",
            "value": [
              9.521974161268728
            ]
          }
        ],
        "recordId": "237134ae-eac8-48c3-a249-275d8b0d7bbe"
      },
      "durationInMs": 49,
      "timeFrame": {
        "startTimestamp": "2023-03-14T22:47:02.258078Z",
        "endTimestamp": "2023-03-14T22:47:02.30766Z"
      }
    },
    {
      "taskName": "Task: 5",
      "sourceInformation": {
        "url": "http://localhost:8082"
      },
      "threadName": "pool-1-thread-2",
      "record": {
        "kvPairs": [
          {
            "key": "F",
            "value": [
              "ojL"
            ]
          },
          {
            "key": "staticKeyDynStringValue",
            "value": [
              "HDAp"
            ]
          },
          {
            "key": "dwGxRWN",
            "value": [
              "H"
            ]
          },
          {
            "key": "staticKeyDynStringEnumDynValue",
            "value": [
              "j"
            ]
          },
          {
            "key": "p",
            "value": [
              "s-val1"
